In [13]:
import numpy as np

In [14]:
# Numpy es la sigla numerical Python
# tenemos librerias que vienen al instalar python, pero hay otras librerias externas que tenemos que instalar
# pip es un seitema de gestion de paquetes
# tenemos varias estructiras de datos, una de ellas son lo arrays
# Array escalar como temperaturas
# bidimencional son matrices
# array de mas de 3 dimensciones que se los reconoce como tensor


In [15]:
# asi se empiexan a trbajar con arrays
my_list = [1, 2, 3, 4, 5, 6]
arr = np.array(my_list)
print(arr)
print(my_list)

[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]


In [16]:
arr = np.arange(start=1, stop=11, step=1) #el arange no toma el ultima posicion
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
arr = np.linspace(start=1, stop=99, num=100) #si tuene en cuenta el ultimo elemento
print(arr)

[ 1.          1.98989899  2.97979798  3.96969697  4.95959596  5.94949495
  6.93939394  7.92929293  8.91919192  9.90909091 10.8989899  11.88888889
 12.87878788 13.86868687 14.85858586 15.84848485 16.83838384 17.82828283
 18.81818182 19.80808081 20.7979798  21.78787879 22.77777778 23.76767677
 24.75757576 25.74747475 26.73737374 27.72727273 28.71717172 29.70707071
 30.6969697  31.68686869 32.67676768 33.66666667 34.65656566 35.64646465
 36.63636364 37.62626263 38.61616162 39.60606061 40.5959596  41.58585859
 42.57575758 43.56565657 44.55555556 45.54545455 46.53535354 47.52525253
 48.51515152 49.50505051 50.49494949 51.48484848 52.47474747 53.46464646
 54.45454545 55.44444444 56.43434343 57.42424242 58.41414141 59.4040404
 60.39393939 61.38383838 62.37373737 63.36363636 64.35353535 65.34343434
 66.33333333 67.32323232 68.31313131 69.3030303  70.29292929 71.28282828
 72.27272727 73.26262626 74.25252525 75.24242424 76.23232323 77.22222222
 78.21212121 79.2020202  80.19191919 81.18181818 82.

In [19]:
arr = np.zeros(10)
print(arr)
#crea un array de ceros

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
