# Práctica Clase 3

## Numpy

In [2]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [3]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [6]:
lista = list(range(8))
lista_2 = []
for i in range(8):
    lista_2.append(i)
print(lista)
print(lista_2)

[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7]


In [16]:
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [17]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [18]:
arreglo += 1

In [19]:
arreglo

array([1, 2, 3, 4, 5, 6, 7, 8])

2. Elevar al cuadrado todos los elementos

In [20]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [21]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36, 49, 64])

3. Sumar todos los elementos

In [22]:
print(arreglo.sum())
print(lista.sum())

36


AttributeError: 'list' object has no attribute 'sum'

In [24]:
sum(lista)

28

In [23]:
n = 0
for e in lista:
    n = n + e
print(n)

28


In [26]:
len(lista)

8

In [32]:
arreglo.shape

(1, 6)

In [27]:
arreglo.ndim

1

In [28]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [30]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [29]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [30]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [33]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [34]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [36]:
a2 = a1.copy()
a2.shape

(2, 4)

In [37]:
a3 = a1 * a2
a3.shape

(2, 4)

In [44]:
np.array([[0,1,2,3,4,5,6]])

array([[0, 1, 2, 3, 4, 5, 6]])

In [48]:
np.array([[0,1,2,3,4,5,6], [2,2,2,2,2,2,2]])

array([[0, 1, 2, 3, 4, 5, 6],
       [2, 2, 2, 2, 2, 2, 2]])

In [39]:
a3, a2, a1

(array([[ 1,  4,  9, 16],
        [25, 36, 49, 64]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [50]:
arreglo_1 = np.arange(0,10)
print(arreglo_1)

[0 1 2 3 4 5 6 7 8 9]


In [51]:
arreglo_2 = np.linspace(0,9, 100)
print(arreglo_2)
print(len(arreglo_2))

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [52]:
a = np.arange(10,101)
a

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
a = a.reshape(3,3,10)

In [71]:
mask = (a%3==0) & (a > 90) #Creamos la máscara (filtro)
mask1 = a > 90

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False])

In [56]:
mask.shape

(91,)

In [69]:
b = a[mask & mask1]

In [70]:
b

array([93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [82]:
zeros = np.zeros((5,10), dtype = int)
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [86]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [83]:
zeros[[1,3,4],:]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [84]:
#zeros[1] = np.ones(10)
#zeros

In [85]:
zeros[[1,4],:] = 1
zeros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [100]:
zeros[:,5] = 50000
zeros

array([[    0,     5,   100,   100,     5, 50000,     5,     5,     5,
            5],
       [   10,    10,   100,   100,    10, 50000,    10,    10,    10,
           10],
       [    5,     5,   100,   100,     5, 50000,     5,     5,     5,
            5],
       [    5,     5,   100,   100,     5, 50000,     5,     5,     5,
            5],
       [    5,     5,   100,   100,     5, 50000,     5,     5,     5,
            5]])

In [88]:
todos = []
n = 0
lat = -90
long = -180
while lat < 91:
    while long < 181:
        todos.append([lat,long])
        n = n + 1
        long = long + 1          
    long = -180
    lat = lat + 1
print(n)

65341


In [101]:
todos = np.array(todos)

In [103]:
todos.shape

(65341, 2)

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [106]:
np.random.random((4,2,3)) 

array([[[0.9350868 , 0.29032261, 0.63330543],
        [0.98126758, 0.13728714, 0.0526147 ]],

       [[0.9907151 , 0.48423028, 0.92005369],
        [0.13436982, 0.32280279, 0.65937654]],

       [[0.4447772 , 0.30852463, 0.6354298 ],
        [0.3191204 , 0.54220126, 0.06618827]],

       [[0.1873257 , 0.78863284, 0.52579745],
        [0.31115066, 0.30029356, 0.71122761]]])

In [107]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[113.70774684, 113.52196174, 133.59489187],
        [197.90131254, 135.40265451, 155.12910125]],

       [[163.37167612, 117.36739711, 114.82333277],
        [115.63413733, 137.14558064, 104.68959281]],

       [[175.91163581, 194.76828233, 139.46555665],
        [108.94477526, 195.13773827, 157.10960569]],

       [[107.69315713, 126.78400546, 105.31281955],
        [113.8179883 , 146.08772355, 175.60700745]]])

In [108]:
a = np.random.random((4,4))

In [109]:
a

array([[0.56014104, 0.73305737, 0.80889617, 0.64441174],
       [0.78146186, 0.23220022, 0.88071578, 0.1404756 ],
       [0.6051292 , 0.62708112, 0.73113637, 0.74618114],
       [0.71137597, 0.48560774, 0.23833624, 0.33810144]])

In [144]:
a = np.array([[10,200,150,100,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [139]:
a

array([[  10,  -56, -106,   45,    5,   50],
       [   5,   20,   30,   40,   50,    0],
       [   5,   20,   30,   40,   50,    0],
       [   5,   20,   30,   40,   50,    0]], dtype=int8)

In [114]:
a.mean()

21.625

In [112]:
a.sum()

519

In [113]:
a.std()

23.924904214367643

In [115]:
a.sort(axis=1)

In [116]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [118]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [117]:
a.sort(axis = 0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [119]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [120]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [125]:
a = np.array([l])

In [127]:
a

array([[[ 10, 200,  30,  45,   5, 100],
        [  5,  20,  30,  40,  50,   0],
        [  5,  20,  30,  40,  50,   0],
        [  5,  20,  30,  40,  50,   0]]])

In [126]:
a.shape

(1, 4, 6)

In [128]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [129]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

[[1 2 3 4 5 6]]


In [130]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [131]:
a.shape, b.shape

((1, 6), (6, 1))

In [132]:
c = a * b 
print(c) 

[[91]]


In [133]:
d = b * a 
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [134]:
b.shape

(6, 1)

In [135]:
a.shape

(1, 6)

In [145]:
matriz_david = np.array([[1,2,4,'i',2],
                [1,2,3,'j','h'],
                [1,2,3,4,5]])

In [147]:
matriz_david

array([['1', '2', '4', 'i', '2'],
       ['1', '2', '3', 'j', 'h'],
       ['1', '2', '3', '4', '5']], dtype='<U11')

In [151]:
'i'.isdigit()

False